### ISSUE TITLE
Edition of rounds issues

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#269]
- [x] I update the sequence of parcels on regression test in the flow preset rounds (rounds of the 20/06). On save I can see the spinning wheel on the rounds but it never ends and I never receive a feedback saying the save has been done.
- [x] Idem when I move parcels from a round to another
- [x] When I reassign a driver, I save, I should receive a user confirmation to confirm the save has been done
- [x] I should also receive a validation modal when I delete a round, after I save.
- [x] Sometimes I move parcel from a round to another and I cannot see the spinning wheel after saving the rounds

**Comment by MelanieApplincourt** [comment]
![screen shot 2016-06-20 at 12 24 46](https://cloud.githubusercontent.com/assets/2649355/16190957/20b9d5f4-36e2-11e6-92ee-229da2e342fc.png)

**Comment by GuillaumeGolinvaux** [comment]
Update ok BUT:
- [ ] when I have an **empty round**, it gives the message optimized partially because no parcels are in the round. But the spinning wheel is still there on that empty round
  ![image](https://cloud.githubusercontent.com/assets/18420928/16295243/ea955cbe-3925-11e6-822b-e8790f425d3c.png)
  Other changes aftewards cannot be saved
  ![image](https://cloud.githubusercontent.com/assets/18420928/16295263/1120dfe8-3926-11e6-8600-f77cd88e25d2.png)
- [ ] When I change a driver and save it **works the first time**. But when I change it again, I press save, and nothing happens. Coming back in the app and I see that the change was not done.
  ![image](https://cloud.githubusercontent.com/assets/18420928/16295776/02e01176-3929-11e6-997f-3cc8d977079e.png)

**Comment by domitien** [comment]
Ok
