### ISSUE TITLE
Edit round / parcels status management

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#42]
A parcel has been moved from an existing round to a new one. The moved parcel should be "awaiting arrival" or "arrived", depending on the flux. At the moment is is geocoded.
- [ ] A parcel is moved from a round => geocoded
- [ ] A parcel is added to a round => awaiting arrival or arrived (based on the flux configuration)

**Comment by GuillaumeGolinvaux** [comment]
now:

A parcel removed from a round: Geocoded
A parcel moved to another round: Awaiting arrival (flow with dispatch)

==> OK

**Comment by MelanieApplincourt** [comment]
I tested this morning and it's not working properly, on the driver app and round editor in the web app, when I remove a parcel from a round (to become orphan), this parcel is still in its original status whereas it should be in geocoded.
ex: regression test, 27/04, parcel 1330221000014

**Comment by Justinuz** [comment]
Done

**Comment by MelanieApplincourt** [comment]
It's not completely OK. The final status is good but the history does not match the status. In the parcel list the parcel appears as geocoded but in the history it is pending delivery:
![screen shot 2016-04-27 at 20 54 31](https://cloud.githubusercontent.com/assets/2649355/14864510/7739c472-0cba-11e6-8d60-f67814f603b9.png)
![screen shot 2016-04-27 at 20 54 39](https://cloud.githubusercontent.com/assets/2649355/14864521/7d35a53a-0cba-11e6-9a50-241fb007d3e2.png)

**Comment by ventur** [comment]
Just a remark, 
if the parcel you removed from the round is a delivery service and the parcel has a pickup service, the status shouldn't change to geocoded, it should stay in the same status as it was because the pickup service is served before the delivery. In that case, a new optim for the delivery won't change the status, it will just add the parcel to the new round in a specific sequence. 
If the removed service is pickup or a delivery without pickup, the parcel should change to geocoded.

**Comment by Justinuz** [comment]
Do do do do do do DOOOOOOOOOOOOOOOOOOOOOOONE

**Comment by MelanieApplincourt** [comment]
OK
